// <auto-generated />
using EroskiApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EroskiApi.Migrations
{
    [DbContext(typeof(EroskiContext))]
    [Migration("20211220073923_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EroskiApi.Models.Eroski", b =>
                {
                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Ticket")
                        .HasColumnType("bigint");

                    b.HasKey("Seccion");

                    b.ToTable("Eroski");
                });
#pragma warning restore 612, 618
        }
    }
}
